spring.application.name=Chatter
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus_ai_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.DriverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- AI (Ollama) ---
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=nomic-embed-text
gemini.api.key=AIzaSyBq-YhsEfqpH4Hyb_FnXnenbChLBQLmtr4

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://eager-viper-53.clerk.accounts.dev

CLERK_SECRET_KEY=

