spring.application.name=Chatter
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus_ai_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.DriverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=
CLERK_SECRET_KEY=